import type { MyRow } from "./grid-data";

/**
 * Pre-defined static rows that are consistent across page loads.
 * These 100 rows will always be used first when generating mock data.
 */
export const STATIC_ROWS: MyRow[] = [
	{
		id: "static-001",
		lastUpdated: "1733400000000",
		text: "Implement authentication",
		status: "Not Started",
		tags: ["Feature"],
		assignee: "John Doe",
		priority: "High",
	},
	{
		id: "static-002",
		lastUpdated: "1733400100000",
		text: "Fix login redirect bug",
		status: "In Progress",
		tags: ["Bug"],
		assignee: "Jane Smith",
		priority: "High",
	},
	{
		id: "static-003",
		lastUpdated: "1733400200000",
		text: "Update API documentation",
		status: "Completed",
		tags: ["Documentation"],
		assignee: "Alice Johnson",
		priority: "Low",
	},
	{
		id: "static-004",
		lastUpdated: "1733400300000",
		text: "Refactor database queries",
		status: "Cancelled",
		tags: ["Refactoring"],
		assignee: "Bob Brown",
		priority: "Medium",
	},
	{
		id: "static-005",
		lastUpdated: "1733400400000",
		text: "Add unit tests for auth module",
		status: "Not Started",
		tags: ["Testing"],
		assignee: "John Doe",
		priority: "Medium",
	},
	{
		id: "static-006",
		lastUpdated: "1733400500000",
		text: "Configure CI/CD pipeline",
		status: "In Progress",
		tags: ["Other"],
		assignee: "Jane Smith",
		priority: "High",
	},
	{
		id: "static-007",
		lastUpdated: "1733400600000",
		text: "Optimize dashboard performance",
		status: "Completed",
		tags: ["Feature", "Refactoring"],
		assignee: "Alice Johnson",
		priority: "High",
	},
	{
		id: "static-008",
		lastUpdated: "1733400700000",
		text: "Fix pagination bug in reports",
		status: "Not Started",
		tags: ["Bug"],
		assignee: "Bob Brown",
		priority: "Medium",
	},
	{
		id: "static-009",
		lastUpdated: "1733400800000",
		text: "Add search functionality",
		status: "In Progress",
		tags: ["Feature"],
		assignee: "John Doe",
		priority: "High",
	},
	{
		id: "static-010",
		lastUpdated: "1733400900000",
		text: "Write integration tests",
		status: "Cancelled",
		tags: ["Testing"],
		assignee: "Jane Smith",
		priority: "Low",
	},
	{
		id: "static-011",
		lastUpdated: "1733401000000",
		text: "Update user settings page",
		status: "Completed",
		tags: ["Feature"],
		assignee: "Alice Johnson",
		priority: "Medium",
	},
	{
		id: "static-012",
		lastUpdated: "1733401100000",
		text: "Fix notification delivery",
		status: "Not Started",
		tags: ["Bug", "Feature"],
		assignee: "Bob Brown",
		priority: "High",
	},
	{
		id: "static-013",
		lastUpdated: "1733401200000",
		text: "Document API endpoints",
		status: "In Progress",
		tags: ["Documentation"],
		assignee: "John Doe",
		priority: "Low",
	},
	{
		id: "static-014",
		lastUpdated: "1733401300000",
		text: "Refactor error handling",
		status: "Completed",
		tags: ["Refactoring"],
		assignee: "Jane Smith",
		priority: "Medium",
	},
	{
		id: "static-015",
		lastUpdated: "1733401400000",
		text: "Add export to CSV feature",
		status: "Cancelled",
		tags: ["Feature"],
		assignee: "Alice Johnson",
		priority: "Low",
	},
	{
		id: "static-016",
		lastUpdated: "1733401500000",
		text: "Fix mobile responsive layout",
		status: "Not Started",
		tags: ["Bug"],
		assignee: "Bob Brown",
		priority: "High",
	},
	{
		id: "static-017",
		lastUpdated: "1733401600000",
		text: "Implement caching layer",
		status: "In Progress",
		tags: ["Feature", "Refactoring"],
		assignee: "John Doe",
		priority: "High",
	},
	{
		id: "static-018",
		lastUpdated: "1733401700000",
		text: "Add end-to-end tests",
		status: "Completed",
		tags: ["Testing"],
		assignee: "Jane Smith",
		priority: "Medium",
	},
	{
		id: "static-019",
		lastUpdated: "1733401800000",
		text: "Update README file",
		status: "Not Started",
		tags: ["Documentation"],
		assignee: "Alice Johnson",
		priority: "Low",
	},
	{
		id: "static-020",
		lastUpdated: "1733401900000",
		text: "Fix date formatting bug",
		status: "Cancelled",
		tags: ["Bug"],
		assignee: "Bob Brown",
		priority: "Low",
	},
	{
		id: "static-021",
		lastUpdated: "1733402000000",
		text: "Add dark mode support",
		status: "In Progress",
		tags: ["Feature"],
		assignee: "John Doe",
		priority: "Medium",
	},
	{
		id: "static-022",
		lastUpdated: "1733402100000",
		text: "Refactor validation logic",
		status: "Completed",
		tags: ["Refactoring"],
		assignee: "Jane Smith",
		priority: "Low",
	},
	{
		id: "static-023",
		lastUpdated: "1733402200000",
		text: "Fix memory leak in dashboard",
		status: "Not Started",
		tags: ["Bug", "Refactoring"],
		assignee: "Alice Johnson",
		priority: "High",
	},
	{
		id: "static-024",
		lastUpdated: "1733402300000",
		text: "Add logging middleware",
		status: "In Progress",
		tags: ["Feature"],
		assignee: "Bob Brown",
		priority: "Medium",
	},
	{
		id: "static-025",
		lastUpdated: "1733402400000",
		text: "Write API usage guide",
		status: "Cancelled",
		tags: ["Documentation"],
		assignee: "John Doe",
		priority: "Low",
	},
	{
		id: "static-026",
		lastUpdated: "1733402500000",
		text: "Implement rate limiting",
		status: "Completed",
		tags: ["Feature", "Other"],
		assignee: "Jane Smith",
		priority: "High",
	},
	{
		id: "static-027",
		lastUpdated: "1733402600000",
		text: "Add snapshot tests",
		status: "Not Started",
		tags: ["Testing"],
		assignee: "Alice Johnson",
		priority: "Medium",
	},
	{
		id: "static-028",
		lastUpdated: "1733402700000",
		text: "Fix CORS configuration",
		status: "In Progress",
		tags: ["Bug"],
		assignee: "Bob Brown",
		priority: "High",
	},
	{
		id: "static-029",
		lastUpdated: "1733402800000",
		text: "Refactor component structure",
		status: "Completed",
		tags: ["Refactoring"],
		assignee: "John Doe",
		priority: "Medium",
	},
	{
		id: "static-030",
		lastUpdated: "1733402900000",
		text: "Add user profile feature",
		status: "Cancelled",
		tags: ["Feature"],
		assignee: "Jane Smith",
		priority: "Medium",
	},
	{
		id: "static-031",
		lastUpdated: "1733403000000",
		text: "Update deployment docs",
		status: "Not Started",
		tags: ["Documentation"],
		assignee: "Alice Johnson",
		priority: "Low",
	},
	{
		id: "static-032",
		lastUpdated: "1733403100000",
		text: "Fix session timeout issue",
		status: "In Progress",
		tags: ["Bug"],
		assignee: "Bob Brown",
		priority: "High",
	},
	{
		id: "static-033",
		lastUpdated: "1733403200000",
		text: "Add performance monitoring",
		status: "Completed",
		tags: ["Feature", "Testing"],
		assignee: "John Doe",
		priority: "Medium",
	},
	{
		id: "static-034",
		lastUpdated: "1733403300000",
		text: "Refactor state management",
		status: "Not Started",
		tags: ["Refactoring"],
		assignee: "Jane Smith",
		priority: "High",
	},
	{
		id: "static-035",
		lastUpdated: "1733403400000",
		text: "Write component docs",
		status: "Cancelled",
		tags: ["Documentation"],
		assignee: "Alice Johnson",
		priority: "Low",
	},
	{
		id: "static-036",
		lastUpdated: "1733403500000",
		text: "Fix filter reset bug",
		status: "In Progress",
		tags: ["Bug"],
		assignee: "Bob Brown",
		priority: "Medium",
	},
	{
		id: "static-037",
		lastUpdated: "1733403600000",
		text: "Implement bulk actions",
		status: "Completed",
		tags: ["Feature"],
		assignee: "John Doe",
		priority: "High",
	},
	{
		id: "static-038",
		lastUpdated: "1733403700000",
		text: "Add accessibility tests",
		status: "Not Started",
		tags: ["Testing", "Other"],
		assignee: "Jane Smith",
		priority: "Medium",
	},
	{
		id: "static-039",
		lastUpdated: "1733403800000",
		text: "Update error messages",
		status: "In Progress",
		tags: ["Feature"],
		assignee: "Alice Johnson",
		priority: "Low",
	},
	{
		id: "static-040",
		lastUpdated: "1733403900000",
		text: "Fix dropdown z-index issue",
		status: "Cancelled",
		tags: ["Bug"],
		assignee: "Bob Brown",
		priority: "Low",
	},
	{
		id: "static-041",
		lastUpdated: "1733404000000",
		text: "Refactor API client",
		status: "Completed",
		tags: ["Refactoring"],
		assignee: "John Doe",
		priority: "Medium",
	},
	{
		id: "static-042",
		lastUpdated: "1733404100000",
		text: "Add import from JSON",
		status: "Not Started",
		tags: ["Feature"],
		assignee: "Jane Smith",
		priority: "Medium",
	},
	{
		id: "static-043",
		lastUpdated: "1733404200000",
		text: "Document testing strategy",
		status: "In Progress",
		tags: ["Documentation", "Testing"],
		assignee: "Alice Johnson",
		priority: "Low",
	},
	{
		id: "static-044",
		lastUpdated: "1733404300000",
		text: "Fix table sorting bug",
		status: "Completed",
		tags: ["Bug"],
		assignee: "Bob Brown",
		priority: "High",
	},
	{
		id: "static-045",
		lastUpdated: "1733404400000",
		text: "Add keyboard shortcuts",
		status: "Cancelled",
		tags: ["Feature"],
		assignee: "John Doe",
		priority: "Low",
	},
	{
		id: "static-046",
		lastUpdated: "1733404500000",
		text: "Implement auto-save",
		status: "Not Started",
		tags: ["Feature"],
		assignee: "Jane Smith",
		priority: "High",
	},
	{
		id: "static-047",
		lastUpdated: "1733404600000",
		text: "Add load tests",
		status: "In Progress",
		tags: ["Testing"],
		assignee: "Alice Johnson",
		priority: "Medium",
	},
	{
		id: "static-048",
		lastUpdated: "1733404700000",
		text: "Refactor form validation",
		status: "Completed",
		tags: ["Refactoring"],
		assignee: "Bob Brown",
		priority: "Medium",
	},
	{
		id: "static-049",
		lastUpdated: "1733404800000",
		text: "Fix timezone handling",
		status: "Not Started",
		tags: ["Bug", "Other"],
		assignee: "John Doe",
		priority: "High",
	},
	{
		id: "static-050",
		lastUpdated: "1733404900000",
		text: "Update security docs",
		status: "Cancelled",
		tags: ["Documentation"],
		assignee: "Jane Smith",
		priority: "Medium",
	},
	{
		id: "static-051",
		lastUpdated: "1733405000000",
		text: "Add role-based access",
		status: "In Progress",
		tags: ["Feature"],
		assignee: "Alice Johnson",
		priority: "High",
	},
	{
		id: "static-052",
		lastUpdated: "1733405100000",
		text: "Fix chart rendering bug",
		status: "Completed",
		tags: ["Bug"],
		assignee: "Bob Brown",
		priority: "Medium",
	},
	{
		id: "static-053",
		lastUpdated: "1733405200000",
		text: "Refactor auth middleware",
		status: "Not Started",
		tags: ["Refactoring"],
		assignee: "John Doe",
		priority: "Medium",
	},
	{
		id: "static-054",
		lastUpdated: "1733405300000",
		text: "Add contract tests",
		status: "In Progress",
		tags: ["Testing"],
		assignee: "Jane Smith",
		priority: "Low",
	},
	{
		id: "static-055",
		lastUpdated: "1733405400000",
		text: "Write onboarding guide",
		status: "Cancelled",
		tags: ["Documentation"],
		assignee: "Alice Johnson",
		priority: "Low",
	},
	{
		id: "static-056",
		lastUpdated: "1733405500000",
		text: "Implement webhooks",
		status: "Completed",
		tags: ["Feature"],
		assignee: "Bob Brown",
		priority: "High",
	},
	{
		id: "static-057",
		lastUpdated: "1733405600000",
		text: "Fix tooltip positioning",
		status: "Not Started",
		tags: ["Bug"],
		assignee: "John Doe",
		priority: "Low",
	},
	{
		id: "static-058",
		lastUpdated: "1733405700000",
		text: "Add audit logging",
		status: "In Progress",
		tags: ["Feature", "Other"],
		assignee: "Jane Smith",
		priority: "High",
	},
	{
		id: "static-059",
		lastUpdated: "1733405800000",
		text: "Refactor query builder",
		status: "Completed",
		tags: ["Refactoring"],
		assignee: "Alice Johnson",
		priority: "Medium",
	},
	{
		id: "static-060",
		lastUpdated: "1733405900000",
		text: "Fix scroll behavior",
		status: "Cancelled",
		tags: ["Bug"],
		assignee: "Bob Brown",
		priority: "Medium",
	},
	{
		id: "static-061",
		lastUpdated: "1733406000000",
		text: "Add regression tests",
		status: "Not Started",
		tags: ["Testing"],
		assignee: "John Doe",
		priority: "Medium",
	},
	{
		id: "static-062",
		lastUpdated: "1733406100000",
		text: "Update architecture docs",
		status: "In Progress",
		tags: ["Documentation"],
		assignee: "Jane Smith",
		priority: "Low",
	},
	{
		id: "static-063",
		lastUpdated: "1733406200000",
		text: "Implement data export",
		status: "Completed",
		tags: ["Feature"],
		assignee: "Alice Johnson",
		priority: "High",
	},
	{
		id: "static-064",
		lastUpdated: "1733406300000",
		text: "Fix input validation",
		status: "Not Started",
		tags: ["Bug", "Refactoring"],
		assignee: "Bob Brown",
		priority: "High",
	},
	{
		id: "static-065",
		lastUpdated: "1733406400000",
		text: "Add batch processing",
		status: "Cancelled",
		tags: ["Feature"],
		assignee: "John Doe",
		priority: "Medium",
	},
	{
		id: "static-066",
		lastUpdated: "1733406500000",
		text: "Refactor event handlers",
		status: "In Progress",
		tags: ["Refactoring"],
		assignee: "Jane Smith",
		priority: "Low",
	},
	{
		id: "static-067",
		lastUpdated: "1733406600000",
		text: "Add security tests",
		status: "Completed",
		tags: ["Testing", "Other"],
		assignee: "Alice Johnson",
		priority: "High",
	},
	{
		id: "static-068",
		lastUpdated: "1733406700000",
		text: "Fix modal focus trap",
		status: "Not Started",
		tags: ["Bug"],
		assignee: "Bob Brown",
		priority: "Medium",
	},
	{
		id: "static-069",
		lastUpdated: "1733406800000",
		text: "Document hook usage",
		status: "In Progress",
		tags: ["Documentation"],
		assignee: "John Doe",
		priority: "Low",
	},
	{
		id: "static-070",
		lastUpdated: "1733406900000",
		text: "Implement real-time sync",
		status: "Cancelled",
		tags: ["Feature"],
		assignee: "Jane Smith",
		priority: "High",
	},
	{
		id: "static-071",
		lastUpdated: "1733407000000",
		text: "Fix image upload bug",
		status: "Completed",
		tags: ["Bug"],
		assignee: "Alice Johnson",
		priority: "Medium",
	},
	{
		id: "static-072",
		lastUpdated: "1733407100000",
		text: "Refactor data fetching",
		status: "Not Started",
		tags: ["Refactoring"],
		assignee: "Bob Brown",
		priority: "High",
	},
	{
		id: "static-073",
		lastUpdated: "1733407200000",
		text: "Add visual tests",
		status: "In Progress",
		tags: ["Testing"],
		assignee: "John Doe",
		priority: "Medium",
	},
	{
		id: "static-074",
		lastUpdated: "1733407300000",
		text: "Write style guide",
		status: "Completed",
		tags: ["Documentation"],
		assignee: "Jane Smith",
		priority: "Low",
	},
	{
		id: "static-075",
		lastUpdated: "1733407400000",
		text: "Add multi-select filter",
		status: "Cancelled",
		tags: ["Feature"],
		assignee: "Alice Johnson",
		priority: "Medium",
	},
	{
		id: "static-076",
		lastUpdated: "1733407500000",
		text: "Fix locale detection",
		status: "Not Started",
		tags: ["Bug", "Feature"],
		assignee: "Bob Brown",
		priority: "Low",
	},
	{
		id: "static-077",
		lastUpdated: "1733407600000",
		text: "Implement lazy loading",
		status: "In Progress",
		tags: ["Feature", "Refactoring"],
		assignee: "John Doe",
		priority: "High",
	},
	{
		id: "static-078",
		lastUpdated: "1733407700000",
		text: "Add smoke tests",
		status: "Completed",
		tags: ["Testing"],
		assignee: "Jane Smith",
		priority: "Medium",
	},
	{
		id: "static-079",
		lastUpdated: "1733407800000",
		text: "Refactor route config",
		status: "Not Started",
		tags: ["Refactoring"],
		assignee: "Alice Johnson",
		priority: "Medium",
	},
	{
		id: "static-080",
		lastUpdated: "1733407900000",
		text: "Fix SSR hydration",
		status: "Cancelled",
		tags: ["Bug"],
		assignee: "Bob Brown",
		priority: "High",
	},
	{
		id: "static-081",
		lastUpdated: "1733408000000",
		text: "Update changelog",
		status: "In Progress",
		tags: ["Documentation"],
		assignee: "John Doe",
		priority: "Low",
	},
	{
		id: "static-082",
		lastUpdated: "1733408100000",
		text: "Add date range picker",
		status: "Completed",
		tags: ["Feature"],
		assignee: "Jane Smith",
		priority: "Medium",
	},
	{
		id: "static-083",
		lastUpdated: "1733408200000",
		text: "Fix form submission",
		status: "Not Started",
		tags: ["Bug"],
		assignee: "Alice Johnson",
		priority: "High",
	},
	{
		id: "static-084",
		lastUpdated: "1733408300000",
		text: "Refactor utility functions",
		status: "In Progress",
		tags: ["Refactoring", "Other"],
		assignee: "Bob Brown",
		priority: "Low",
	},
	{
		id: "static-085",
		lastUpdated: "1733408400000",
		text: "Add mutation tests",
		status: "Cancelled",
		tags: ["Testing"],
		assignee: "John Doe",
		priority: "Low",
	},
	{
		id: "static-086",
		lastUpdated: "1733408500000",
		text: "Document env variables",
		status: "Completed",
		tags: ["Documentation"],
		assignee: "Jane Smith",
		priority: "Medium",
	},
	{
		id: "static-087",
		lastUpdated: "1733408600000",
		text: "Implement file preview",
		status: "Not Started",
		tags: ["Feature"],
		assignee: "Alice Johnson",
		priority: "Medium",
	},
	{
		id: "static-088",
		lastUpdated: "1733408700000",
		text: "Fix infinite scroll",
		status: "In Progress",
		tags: ["Bug"],
		assignee: "Bob Brown",
		priority: "High",
	},
	{
		id: "static-089",
		lastUpdated: "1733408800000",
		text: "Add API mocking",
		status: "Completed",
		tags: ["Testing", "Feature"],
		assignee: "John Doe",
		priority: "Medium",
	},
	{
		id: "static-090",
		lastUpdated: "1733408900000",
		text: "Refactor CSS modules",
		status: "Cancelled",
		tags: ["Refactoring"],
		assignee: "Jane Smith",
		priority: "Medium",
	},
	{
		id: "static-091",
		lastUpdated: "1733409000000",
		text: "Fix drag and drop",
		status: "Not Started",
		tags: ["Bug"],
		assignee: "Alice Johnson",
		priority: "Medium",
	},
	{
		id: "static-092",
		lastUpdated: "1733409100000",
		text: "Write migration guide",
		status: "In Progress",
		tags: ["Documentation"],
		assignee: "Bob Brown",
		priority: "Low",
	},
	{
		id: "static-093",
		lastUpdated: "1733409200000",
		text: "Add custom themes",
		status: "Completed",
		tags: ["Feature"],
		assignee: "John Doe",
		priority: "High",
	},
	{
		id: "static-094",
		lastUpdated: "1733409300000",
		text: "Fix context menu",
		status: "Not Started",
		tags: ["Bug", "Other"],
		assignee: "Jane Smith",
		priority: "Low",
	},
	{
		id: "static-095",
		lastUpdated: "1733409400000",
		text: "Refactor animation logic",
		status: "Cancelled",
		tags: ["Refactoring"],
		assignee: "Alice Johnson",
		priority: "Low",
	},
	{
		id: "static-096",
		lastUpdated: "1733409500000",
		text: "Add stress tests",
		status: "In Progress",
		tags: ["Testing"],
		assignee: "Bob Brown",
		priority: "High",
	},
	{
		id: "static-097",
		lastUpdated: "1733409600000",
		text: "Implement undo/redo",
		status: "Completed",
		tags: ["Feature"],
		assignee: "John Doe",
		priority: "High",
	},
	{
		id: "static-098",
		lastUpdated: "1733409700000",
		text: "Fix browser compat",
		status: "Not Started",
		tags: ["Bug"],
		assignee: "Jane Smith",
		priority: "Medium",
	},
	{
		id: "static-099",
		lastUpdated: "1733409800000",
		text: "Document best practices",
		status: "In Progress",
		tags: ["Documentation"],
		assignee: "Alice Johnson",
		priority: "Medium",
	},
	{
		id: "static-100",
		lastUpdated: "1733409900000",
		text: "Add column reordering",
		status: "Completed",
		tags: ["Feature", "Refactoring"],
		assignee: "Bob Brown",
		priority: "High",
	},
];
