import type { MyRow } from "./grid-data";

/**
 * Pre-defined static rows that are consistent across page loads.
 * These 100 rows will always be used first when generating mock data.
 */
export const STATIC_ROWS: MyRow[] = [
	{
		id: "static-001",
		lastUpdated: "1733400000000",
		text: "Implement authentication 1",
		status: "Not Started",
		tags: ["Feature"],
		assignee: "John Doe",
		priority: "High",
	},
	{
		id: "static-002",
		lastUpdated: "1733400060000",
		text: "Fix database connection 2",
		status: "In Progress",
		tags: ["Bug"],
		assignee: "Jane Smith",
		priority: "High",
	},
	{
		id: "static-003",
		lastUpdated: "1733400120000",
		text: "Refactor API endpoints 3",
		status: "Completed",
		tags: ["Refactoring"],
		assignee: "Alice Johnson",
		priority: "Medium",
	},
	{
		id: "static-004",
		lastUpdated: "1733400180000",
		text: "Add UI components 4",
		status: "Cancelled",
		tags: ["Feature", "Documentation"],
		assignee: "Bob Brown",
		priority: "Low",
	},
	{
		id: "static-005",
		lastUpdated: "1733400240000",
		text: "Update dashboard layout 5",
		status: "Not Started",
		tags: ["Feature"],
		assignee: "John Doe",
		priority: "Medium",
	},
	{
		id: "static-006",
		lastUpdated: "1733400300000",
		text: "Remove deprecated reports 6",
		status: "In Progress",
		tags: ["Refactoring"],
		assignee: "Jane Smith",
		priority: "Low",
	},
	{
		id: "static-007",
		lastUpdated: "1733400360000",
		text: "Optimize notifications 7",
		status: "Completed",
		tags: ["Bug", "Testing"],
		assignee: "Alice Johnson",
		priority: "High",
	},
	{
		id: "static-008",
		lastUpdated: "1733400420000",
		text: "Debug search functionality 8",
		status: "Not Started",
		tags: ["Bug"],
		assignee: "Bob Brown",
		priority: "High",
	},
	{
		id: "static-009",
		lastUpdated: "1733400480000",
		text: "Test filters performance 9",
		status: "In Progress",
		tags: ["Testing"],
		assignee: "John Doe",
		priority: "Medium",
	},
	{
		id: "static-010",
		lastUpdated: "1733400540000",
		text: "Review export feature 10",
		status: "Completed",
		tags: ["Feature", "Documentation"],
		assignee: "Jane Smith",
		priority: "Low",
	},
	{
		id: "static-011",
		lastUpdated: "1733400600000",
		text: "Deploy import module 11",
		status: "Cancelled",
		tags: ["Feature"],
		assignee: "Alice Johnson",
		priority: "High",
	},
	{
		id: "static-012",
		lastUpdated: "1733400660000",
		text: "Configure settings page 12",
		status: "Not Started",
		tags: ["Feature"],
		assignee: "Bob Brown",
		priority: "Medium",
	},
	{
		id: "static-013",
		lastUpdated: "1733400720000",
		text: "Migrate permissions system 13",
		status: "In Progress",
		tags: ["Refactoring", "Testing"],
		assignee: "John Doe",
		priority: "High",
	},
	{
		id: "static-014",
		lastUpdated: "1733400780000",
		text: "Document logging setup 14",
		status: "Completed",
		tags: ["Documentation"],
		assignee: "Jane Smith",
		priority: "Low",
	},
	{
		id: "static-015",
		lastUpdated: "1733400840000",
		text: "Analyze caching strategy 15",
		status: "Not Started",
		tags: ["Other"],
		assignee: "Alice Johnson",
		priority: "Medium",
	},
	{
		id: "static-016",
		lastUpdated: "1733400900000",
		text: "Design pagination UI 16",
		status: "In Progress",
		tags: ["Feature", "Documentation"],
		assignee: "Bob Brown",
		priority: "High",
	},
	{
		id: "static-017",
		lastUpdated: "1733400960000",
		text: "Build validation rules 17",
		status: "Completed",
		tags: ["Feature"],
		assignee: "John Doe",
		priority: "Medium",
	},
	{
		id: "static-018",
		lastUpdated: "1733401020000",
		text: "Integrate error handling 18",
		status: "Cancelled",
		tags: ["Bug", "Refactoring"],
		assignee: "Jane Smith",
		priority: "High",
	},
	{
		id: "static-019",
		lastUpdated: "1733401080000",
		text: "Validate testing framework 19",
		status: "Not Started",
		tags: ["Testing"],
		assignee: "Alice Johnson",
		priority: "Low",
	},
	{
		id: "static-020",
		lastUpdated: "1733401140000",
		text: "Audit documentation 20",
		status: "In Progress",
		tags: ["Documentation", "Other"],
		assignee: "Bob Brown",
		priority: "Medium",
	},
	{
		id: "static-021",
		lastUpdated: "1733401200000",
		text: "Implement deployment pipeline 21",
		status: "Completed",
		tags: ["Feature"],
		assignee: "John Doe",
		priority: "High",
	},
	{
		id: "static-022",
		lastUpdated: "1733401260000",
		text: "Fix monitoring alerts 22",
		status: "Not Started",
		tags: ["Bug"],
		assignee: "Jane Smith",
		priority: "High",
	},
	{
		id: "static-023",
		lastUpdated: "1733401320000",
		text: "Refactor analytics module 23",
		status: "In Progress",
		tags: ["Refactoring"],
		assignee: "Alice Johnson",
		priority: "Medium",
	},
	{
		id: "static-024",
		lastUpdated: "1733401380000",
		text: "Add performance metrics 24",
		status: "Completed",
		tags: ["Feature", "Testing"],
		assignee: "Bob Brown",
		priority: "Low",
	},
	{
		id: "static-025",
		lastUpdated: "1733401440000",
		text: "Update security policies 25",
		status: "Cancelled",
		tags: ["Documentation"],
		assignee: "John Doe",
		priority: "High",
	},
	{
		id: "static-026",
		lastUpdated: "1733401500000",
		text: "Remove accessibility issues 26",
		status: "Not Started",
		tags: ["Bug", "Feature"],
		assignee: "Jane Smith",
		priority: "Medium",
	},
	{
		id: "static-027",
		lastUpdated: "1733401560000",
		text: "Optimize mobile view 27",
		status: "In Progress",
		tags: ["Feature"],
		assignee: "Alice Johnson",
		priority: "High",
	},
	{
		id: "static-028",
		lastUpdated: "1733401620000",
		text: "Debug authentication flow 28",
		status: "Completed",
		tags: ["Bug", "Testing"],
		assignee: "Bob Brown",
		priority: "High",
	},
	{
		id: "static-029",
		lastUpdated: "1733401680000",
		text: "Test database queries 29",
		status: "Not Started",
		tags: ["Testing"],
		assignee: "John Doe",
		priority: "Medium",
	},
	{
		id: "static-030",
		lastUpdated: "1733401740000",
		text: "Review API documentation 30",
		status: "In Progress",
		tags: ["Documentation"],
		assignee: "Jane Smith",
		priority: "Low",
	},
	{
		id: "static-031",
		lastUpdated: "1733401800000",
		text: "Deploy UI updates 31",
		status: "Completed",
		tags: ["Feature"],
		assignee: "Alice Johnson",
		priority: "High",
	},
	{
		id: "static-032",
		lastUpdated: "1733401860000",
		text: "Configure dashboard widgets 32",
		status: "Cancelled",
		tags: ["Feature", "Other"],
		assignee: "Bob Brown",
		priority: "Medium",
	},
	{
		id: "static-033",
		lastUpdated: "1733401920000",
		text: "Migrate reports system 33",
		status: "Not Started",
		tags: ["Refactoring"],
		assignee: "John Doe",
		priority: "High",
	},
	{
		id: "static-034",
		lastUpdated: "1733401980000",
		text: "Document notifications API 34",
		status: "In Progress",
		tags: ["Documentation"],
		assignee: "Jane Smith",
		priority: "Low",
	},
	{
		id: "static-035",
		lastUpdated: "1733402040000",
		text: "Analyze search performance 35",
		status: "Completed",
		tags: ["Testing", "Other"],
		assignee: "Alice Johnson",
		priority: "Medium",
	},
	{
		id: "static-036",
		lastUpdated: "1733402100000",
		text: "Design filters interface 36",
		status: "Not Started",
		tags: ["Feature"],
		assignee: "Bob Brown",
		priority: "High",
	},
	{
		id: "static-037",
		lastUpdated: "1733402160000",
		text: "Build export functionality 37",
		status: "In Progress",
		tags: ["Feature"],
		assignee: "John Doe",
		priority: "Medium",
	},
	{
		id: "static-038",
		lastUpdated: "1733402220000",
		text: "Integrate import system 38",
		status: "Completed",
		tags: ["Feature", "Refactoring"],
		assignee: "Jane Smith",
		priority: "High",
	},
	{
		id: "static-039",
		lastUpdated: "1733402280000",
		text: "Validate settings schema 39",
		status: "Cancelled",
		tags: ["Testing"],
		assignee: "Alice Johnson",
		priority: "Low",
	},
	{
		id: "static-040",
		lastUpdated: "1733402340000",
		text: "Audit permissions logic 40",
		status: "Not Started",
		tags: ["Refactoring", "Documentation"],
		assignee: "Bob Brown",
		priority: "Medium",
	},
	{
		id: "static-041",
		lastUpdated: "1733402400000",
		text: "Implement logging service 41",
		status: "In Progress",
		tags: ["Feature"],
		assignee: "John Doe",
		priority: "High",
	},
	{
		id: "static-042",
		lastUpdated: "1733402460000",
		text: "Fix caching issues 42",
		status: "Completed",
		tags: ["Bug"],
		assignee: "Jane Smith",
		priority: "High",
	},
	{
		id: "static-043",
		lastUpdated: "1733402520000",
		text: "Refactor pagination logic 43",
		status: "Not Started",
		tags: ["Refactoring"],
		assignee: "Alice Johnson",
		priority: "Medium",
	},
	{
		id: "static-044",
		lastUpdated: "1733402580000",
		text: "Add validation messages 44",
		status: "In Progress",
		tags: ["Feature", "Bug"],
		assignee: "Bob Brown",
		priority: "Low",
	},
	{
		id: "static-045",
		lastUpdated: "1733402640000",
		text: "Update error handling 45",
		status: "Completed",
		tags: ["Refactoring"],
		assignee: "John Doe",
		priority: "High",
	},
	{
		id: "static-046",
		lastUpdated: "1733402700000",
		text: "Remove testing utilities 46",
		status: "Cancelled",
		tags: ["Testing", "Other"],
		assignee: "Jane Smith",
		priority: "Medium",
	},
	{
		id: "static-047",
		lastUpdated: "1733402760000",
		text: "Optimize documentation build 47",
		status: "Not Started",
		tags: ["Documentation"],
		assignee: "Alice Johnson",
		priority: "Low",
	},
	{
		id: "static-048",
		lastUpdated: "1733402820000",
		text: "Debug deployment script 48",
		status: "In Progress",
		tags: ["Bug"],
		assignee: "Bob Brown",
		priority: "High",
	},
	{
		id: "static-049",
		lastUpdated: "1733402880000",
		text: "Test monitoring integration 49",
		status: "Completed",
		tags: ["Testing"],
		assignee: "John Doe",
		priority: "Medium",
	},
	{
		id: "static-050",
		lastUpdated: "1733402940000",
		text: "Review analytics dashboard 50",
		status: "Not Started",
		tags: ["Feature", "Documentation"],
		assignee: "Jane Smith",
		priority: "High",
	},
	{
		id: "static-051",
		lastUpdated: "1733403000000",
		text: "Deploy performance fixes 51",
		status: "In Progress",
		tags: ["Bug"],
		assignee: "Alice Johnson",
		priority: "High",
	},
	{
		id: "static-052",
		lastUpdated: "1733403060000",
		text: "Configure security headers 52",
		status: "Completed",
		tags: ["Feature"],
		assignee: "Bob Brown",
		priority: "Medium",
	},
	{
		id: "static-053",
		lastUpdated: "1733403120000",
		text: "Migrate accessibility fixes 53",
		status: "Cancelled",
		tags: ["Bug", "Refactoring"],
		assignee: "John Doe",
		priority: "Low",
	},
	{
		id: "static-054",
		lastUpdated: "1733403180000",
		text: "Document mobile view API 54",
		status: "Not Started",
		tags: ["Documentation"],
		assignee: "Jane Smith",
		priority: "High",
	},
	{
		id: "static-055",
		lastUpdated: "1733403240000",
		text: "Analyze authentication logs 55",
		status: "In Progress",
		tags: ["Other"],
		assignee: "Alice Johnson",
		priority: "Medium",
	},
	{
		id: "static-056",
		lastUpdated: "1733403300000",
		text: "Design database schema 56",
		status: "Completed",
		tags: ["Feature", "Documentation"],
		assignee: "Bob Brown",
		priority: "High",
	},
	{
		id: "static-057",
		lastUpdated: "1733403360000",
		text: "Build API gateway 57",
		status: "Not Started",
		tags: ["Feature"],
		assignee: "John Doe",
		priority: "High",
	},
	{
		id: "static-058",
		lastUpdated: "1733403420000",
		text: "Integrate UI framework 58",
		status: "In Progress",
		tags: ["Feature", "Refactoring"],
		assignee: "Jane Smith",
		priority: "Medium",
	},
	{
		id: "static-059",
		lastUpdated: "1733403480000",
		text: "Validate dashboard data 59",
		status: "Completed",
		tags: ["Testing"],
		assignee: "Alice Johnson",
		priority: "Low",
	},
	{
		id: "static-060",
		lastUpdated: "1733403540000",
		text: "Audit reports generation 60",
		status: "Cancelled",
		tags: ["Testing", "Other"],
		assignee: "Bob Brown",
		priority: "High",
	},
	{
		id: "static-061",
		lastUpdated: "1733403600000",
		text: "Implement notifications service 61",
		status: "Not Started",
		tags: ["Feature"],
		assignee: "John Doe",
		priority: "Medium",
	},
	{
		id: "static-062",
		lastUpdated: "1733403660000",
		text: "Fix search indexing 62",
		status: "In Progress",
		tags: ["Bug"],
		assignee: "Jane Smith",
		priority: "High",
	},
	{
		id: "static-063",
		lastUpdated: "1733403720000",
		text: "Refactor filters logic 63",
		status: "Completed",
		tags: ["Refactoring"],
		assignee: "Alice Johnson",
		priority: "Medium",
	},
	{
		id: "static-064",
		lastUpdated: "1733403780000",
		text: "Add export formats 64",
		status: "Not Started",
		tags: ["Feature", "Documentation"],
		assignee: "Bob Brown",
		priority: "Low",
	},
	{
		id: "static-065",
		lastUpdated: "1733403840000",
		text: "Update import validation 65",
		status: "In Progress",
		tags: ["Bug", "Feature"],
		assignee: "John Doe",
		priority: "High",
	},
	{
		id: "static-066",
		lastUpdated: "1733403900000",
		text: "Remove settings migration 66",
		status: "Completed",
		tags: ["Refactoring"],
		assignee: "Jane Smith",
		priority: "Medium",
	},
	{
		id: "static-067",
		lastUpdated: "1733403960000",
		text: "Optimize permissions check 67",
		status: "Cancelled",
		tags: ["Bug"],
		assignee: "Alice Johnson",
		priority: "High",
	},
	{
		id: "static-068",
		lastUpdated: "1733404020000",
		text: "Debug logging output 68",
		status: "Not Started",
		tags: ["Bug", "Testing"],
		assignee: "Bob Brown",
		priority: "Low",
	},
	{
		id: "static-069",
		lastUpdated: "1733404080000",
		text: "Test caching layer 69",
		status: "In Progress",
		tags: ["Testing"],
		assignee: "John Doe",
		priority: "Medium",
	},
	{
		id: "static-070",
		lastUpdated: "1733404140000",
		text: "Review pagination UX 70",
		status: "Completed",
		tags: ["Feature", "Other"],
		assignee: "Jane Smith",
		priority: "High",
	},
	{
		id: "static-071",
		lastUpdated: "1733404200000",
		text: "Deploy validation rules 71",
		status: "Not Started",
		tags: ["Feature"],
		assignee: "Alice Johnson",
		priority: "High",
	},
	{
		id: "static-072",
		lastUpdated: "1733404260000",
		text: "Configure error tracking 72",
		status: "In Progress",
		tags: ["Feature"],
		assignee: "Bob Brown",
		priority: "Medium",
	},
	{
		id: "static-073",
		lastUpdated: "1733404320000",
		text: "Migrate testing suite 73",
		status: "Completed",
		tags: ["Testing", "Refactoring"],
		assignee: "John Doe",
		priority: "Low",
	},
	{
		id: "static-074",
		lastUpdated: "1733404380000",
		text: "Document documentation style 74",
		status: "Cancelled",
		tags: ["Documentation"],
		assignee: "Jane Smith",
		priority: "Medium",
	},
	{
		id: "static-075",
		lastUpdated: "1733404440000",
		text: "Analyze deployment metrics 75",
		status: "Not Started",
		tags: ["Other"],
		assignee: "Alice Johnson",
		priority: "High",
	},
	{
		id: "static-076",
		lastUpdated: "1733404500000",
		text: "Design monitoring dashboard 76",
		status: "In Progress",
		tags: ["Feature", "Documentation"],
		assignee: "Bob Brown",
		priority: "High",
	},
	{
		id: "static-077",
		lastUpdated: "1733404560000",
		text: "Build analytics pipeline 77",
		status: "Completed",
		tags: ["Feature"],
		assignee: "John Doe",
		priority: "Medium",
	},
	{
		id: "static-078",
		lastUpdated: "1733404620000",
		text: "Integrate performance tools 78",
		status: "Not Started",
		tags: ["Feature", "Testing"],
		assignee: "Jane Smith",
		priority: "High",
	},
	{
		id: "static-079",
		lastUpdated: "1733404680000",
		text: "Validate security audit 79",
		status: "In Progress",
		tags: ["Testing"],
		assignee: "Alice Johnson",
		priority: "Low",
	},
	{
		id: "static-080",
		lastUpdated: "1733404740000",
		text: "Audit accessibility compliance 80",
		status: "Completed",
		tags: ["Bug", "Documentation"],
		assignee: "Bob Brown",
		priority: "Medium",
	},
	{
		id: "static-081",
		lastUpdated: "1733404800000",
		text: "Implement mobile responsive 81",
		status: "Cancelled",
		tags: ["Feature"],
		assignee: "John Doe",
		priority: "High",
	},
	{
		id: "static-082",
		lastUpdated: "1733404860000",
		text: "Fix authentication timeout 82",
		status: "Not Started",
		tags: ["Bug"],
		assignee: "Jane Smith",
		priority: "High",
	},
	{
		id: "static-083",
		lastUpdated: "1733404920000",
		text: "Refactor database queries 83",
		status: "In Progress",
		tags: ["Refactoring"],
		assignee: "Alice Johnson",
		priority: "Medium",
	},
	{
		id: "static-084",
		lastUpdated: "1733404980000",
		text: "Add API rate limiting 84",
		status: "Completed",
		tags: ["Feature", "Bug"],
		assignee: "Bob Brown",
		priority: "High",
	},
	{
		id: "static-085",
		lastUpdated: "1733405040000",
		text: "Update UI theme 85",
		status: "Not Started",
		tags: ["Feature"],
		assignee: "John Doe",
		priority: "Low",
	},
	{
		id: "static-086",
		lastUpdated: "1733405100000",
		text: "Remove dashboard widgets 86",
		status: "In Progress",
		tags: ["Refactoring", "Other"],
		assignee: "Jane Smith",
		priority: "Medium",
	},
	{
		id: "static-087",
		lastUpdated: "1733405160000",
		text: "Optimize reports query 87",
		status: "Completed",
		tags: ["Bug"],
		assignee: "Alice Johnson",
		priority: "High",
	},
	{
		id: "static-088",
		lastUpdated: "1733405220000",
		text: "Debug notifications queue 88",
		status: "Cancelled",
		tags: ["Bug", "Testing"],
		assignee: "Bob Brown",
		priority: "Medium",
	},
	{
		id: "static-089",
		lastUpdated: "1733405280000",
		text: "Test search algorithms 89",
		status: "Not Started",
		tags: ["Testing"],
		assignee: "John Doe",
		priority: "High",
	},
	{
		id: "static-090",
		lastUpdated: "1733405340000",
		text: "Review filters documentation 90",
		status: "In Progress",
		tags: ["Documentation"],
		assignee: "Jane Smith",
		priority: "Low",
	},
	{
		id: "static-091",
		lastUpdated: "1733405400000",
		text: "Deploy export service 91",
		status: "Completed",
		tags: ["Feature"],
		assignee: "Alice Johnson",
		priority: "Medium",
	},
	{
		id: "static-092",
		lastUpdated: "1733405460000",
		text: "Configure import scheduler 92",
		status: "Not Started",
		tags: ["Feature", "Documentation"],
		assignee: "Bob Brown",
		priority: "High",
	},
	{
		id: "static-093",
		lastUpdated: "1733405520000",
		text: "Migrate settings storage 93",
		status: "In Progress",
		tags: ["Refactoring"],
		assignee: "John Doe",
		priority: "High",
	},
	{
		id: "static-094",
		lastUpdated: "1733405580000",
		text: "Document permissions matrix 94",
		status: "Completed",
		tags: ["Documentation"],
		assignee: "Jane Smith",
		priority: "Medium",
	},
	{
		id: "static-095",
		lastUpdated: "1733405640000",
		text: "Analyze logging patterns 95",
		status: "Cancelled",
		tags: ["Other", "Testing"],
		assignee: "Alice Johnson",
		priority: "Low",
	},
	{
		id: "static-096",
		lastUpdated: "1733405700000",
		text: "Design caching strategy 96",
		status: "Not Started",
		tags: ["Feature"],
		assignee: "Bob Brown",
		priority: "High",
	},
	{
		id: "static-097",
		lastUpdated: "1733405760000",
		text: "Build pagination component 97",
		status: "In Progress",
		tags: ["Feature"],
		assignee: "John Doe",
		priority: "Medium",
	},
	{
		id: "static-098",
		lastUpdated: "1733405820000",
		text: "Integrate validation library 98",
		status: "Completed",
		tags: ["Feature", "Refactoring"],
		assignee: "Jane Smith",
		priority: "High",
	},
	{
		id: "static-099",
		lastUpdated: "1733405880000",
		text: "Validate error messages 99",
		status: "Not Started",
		tags: ["Testing", "Bug"],
		assignee: "Alice Johnson",
		priority: "Low",
	},
	{
		id: "static-100",
		lastUpdated: "1733405940000",
		text: "Audit testing coverage 100",
		status: "In Progress",
		tags: ["Testing", "Documentation"],
		assignee: "Bob Brown",
		priority: "Medium",
	},
];
