import type { MyRow } from "./grid-data";

/**
 * Pre-defined static rows that are consistent across page loads.
 * These 100 rows will always be used first when generating mock data.
 */
export const STATIC_ROWS: MyRow[] = [
	{
		id: "static-001",
		lastUpdated: "1733400000000",
		text: "Implement authentication",
		status: "Not Started",
		tags: ["Feature"],
		assignee: "John Doe",
		priority: "High",
	},
	{
		id: "static-002",
		lastUpdated: "1733400060000",
		text: "Fix database connection",
		status: "In Progress",
		tags: ["Bug"],
		assignee: "Jane Smith",
		priority: "High",
	},
	{
		id: "static-003",
		lastUpdated: "1733400120000",
		text: "Refactor API endpoints",
		status: "Completed",
		tags: ["Refactoring"],
		assignee: "Alice Johnson",
		priority: "Medium",
	},
	{
		id: "static-004",
		lastUpdated: "1733400180000",
		text: "Add UI components",
		status: "Cancelled",
		tags: ["Feature", "Documentation"],
		assignee: "Bob Brown",
		priority: "Low",
	},
	{
		id: "static-005",
		lastUpdated: "1733400240000",
		text: "Update dashboard layout",
		status: "Not Started",
		tags: ["Feature"],
		assignee: "John Doe",
		priority: "Medium",
	},
	{
		id: "static-006",
		lastUpdated: "1733400300000",
		text: "Remove deprecated reports",
		status: "In Progress",
		tags: ["Refactoring"],
		assignee: "Jane Smith",
		priority: "Low",
	},
	{
		id: "static-007",
		lastUpdated: "1733400360000",
		text: "Optimize notifications",
		status: "Completed",
		tags: ["Bug", "Testing"],
		assignee: "Alice Johnson",
		priority: "High",
	},
	{
		id: "static-008",
		lastUpdated: "1733400420000",
		text: "Debug search functionality",
		status: "Not Started",
		tags: ["Bug"],
		assignee: "Bob Brown",
		priority: "High",
	},
	{
		id: "static-009",
		lastUpdated: "1733400480000",
		text: "Test filters performance",
		status: "In Progress",
		tags: ["Testing"],
		assignee: "John Doe",
		priority: "Medium",
	},
	{
		id: "static-010",
		lastUpdated: "1733400540000",
		text: "Review export feature",
		status: "Completed",
		tags: ["Feature", "Documentation"],
		assignee: "Jane Smith",
		priority: "Low",
	},
	{
		id: "static-011",
		lastUpdated: "1733400600000",
		text: "Deploy import module",
		status: "Cancelled",
		tags: ["Feature"],
		assignee: "Alice Johnson",
		priority: "High",
	},
	{
		id: "static-012",
		lastUpdated: "1733400660000",
		text: "Configure settings page",
		status: "Not Started",
		tags: ["Feature"],
		assignee: "Bob Brown",
		priority: "Medium",
	},
	{
		id: "static-013",
		lastUpdated: "1733400720000",
		text: "Migrate permissions system",
		status: "In Progress",
		tags: ["Refactoring", "Testing"],
		assignee: "John Doe",
		priority: "High",
	},
	{
		id: "static-014",
		lastUpdated: "1733400780000",
		text: "Document logging setup",
		status: "Completed",
		tags: ["Documentation"],
		assignee: "Jane Smith",
		priority: "Low",
	},
	{
		id: "static-015",
		lastUpdated: "1733400840000",
		text: "Analyze caching strategy",
		status: "Not Started",
		tags: ["Other"],
		assignee: "Alice Johnson",
		priority: "Medium",
	},
	{
		id: "static-016",
		lastUpdated: "1733400900000",
		text: "Design pagination UI",
		status: "In Progress",
		tags: ["Feature", "Documentation"],
		assignee: "Bob Brown",
		priority: "High",
	},
	{
		id: "static-017",
		lastUpdated: "1733400960000",
		text: "Build validation rules",
		status: "Completed",
		tags: ["Feature"],
		assignee: "John Doe",
		priority: "Medium",
	},
	{
		id: "static-018",
		lastUpdated: "1733401020000",
		text: "Integrate error handling",
		status: "Cancelled",
		tags: ["Bug", "Refactoring"],
		assignee: "Jane Smith",
		priority: "High",
	},
	{
		id: "static-019",
		lastUpdated: "1733401080000",
		text: "Validate testing framework",
		status: "Not Started",
		tags: ["Testing"],
		assignee: "Alice Johnson",
		priority: "Low",
	},
	{
		id: "static-020",
		lastUpdated: "1733401140000",
		text: "Audit documentation",
		status: "In Progress",
		tags: ["Documentation", "Other"],
		assignee: "Bob Brown",
		priority: "Medium",
	},
	{
		id: "static-021",
		lastUpdated: "1733401200000",
		text: "Implement deployment pipeline",
		status: "Completed",
		tags: ["Feature"],
		assignee: "John Doe",
		priority: "High",
	},
	{
		id: "static-022",
		lastUpdated: "1733401260000",
		text: "Fix monitoring alerts",
		status: "Not Started",
		tags: ["Bug"],
		assignee: "Jane Smith",
		priority: "High",
	},
	{
		id: "static-023",
		lastUpdated: "1733401320000",
		text: "Refactor analytics module",
		status: "In Progress",
		tags: ["Refactoring"],
		assignee: "Alice Johnson",
		priority: "Medium",
	},
	{
		id: "static-024",
		lastUpdated: "1733401380000",
		text: "Add performance metrics",
		status: "Completed",
		tags: ["Feature", "Testing"],
		assignee: "Bob Brown",
		priority: "Low",
	},
	{
		id: "static-025",
		lastUpdated: "1733401440000",
		text: "Update security policies",
		status: "Cancelled",
		tags: ["Documentation"],
		assignee: "John Doe",
		priority: "High",
	},
	{
		id: "static-026",
		lastUpdated: "1733401500000",
		text: "Remove accessibility issues",
		status: "Not Started",
		tags: ["Bug", "Feature"],
		assignee: "Jane Smith",
		priority: "Medium",
	},
	{
		id: "static-027",
		lastUpdated: "1733401560000",
		text: "Optimize mobile view",
		status: "In Progress",
		tags: ["Feature"],
		assignee: "Alice Johnson",
		priority: "High",
	},
	{
		id: "static-028",
		lastUpdated: "1733401620000",
		text: "Debug authentication flow",
		status: "Completed",
		tags: ["Bug", "Testing"],
		assignee: "Bob Brown",
		priority: "High",
	},
	{
		id: "static-029",
		lastUpdated: "1733401680000",
		text: "Test database queries",
		status: "Not Started",
		tags: ["Testing"],
		assignee: "John Doe",
		priority: "Medium",
	},
	{
		id: "static-030",
		lastUpdated: "1733401740000",
		text: "Review API documentation",
		status: "In Progress",
		tags: ["Documentation"],
		assignee: "Jane Smith",
		priority: "Low",
	},
	{
		id: "static-031",
		lastUpdated: "1733401800000",
		text: "Deploy UI updates",
		status: "Completed",
		tags: ["Feature"],
		assignee: "Alice Johnson",
		priority: "High",
	},
	{
		id: "static-032",
		lastUpdated: "1733401860000",
		text: "Configure dashboard widgets",
		status: "Cancelled",
		tags: ["Feature", "Other"],
		assignee: "Bob Brown",
		priority: "Medium",
	},
	{
		id: "static-033",
		lastUpdated: "1733401920000",
		text: "Migrate reports system",
		status: "Not Started",
		tags: ["Refactoring"],
		assignee: "John Doe",
		priority: "High",
	},
	{
		id: "static-034",
		lastUpdated: "1733401980000",
		text: "Document notifications API",
		status: "In Progress",
		tags: ["Documentation"],
		assignee: "Jane Smith",
		priority: "Low",
	},
	{
		id: "static-035",
		lastUpdated: "1733402040000",
		text: "Analyze search performance",
		status: "Completed",
		tags: ["Testing", "Other"],
		assignee: "Alice Johnson",
		priority: "Medium",
	},
	{
		id: "static-036",
		lastUpdated: "1733402100000",
		text: "Design filters interface",
		status: "Not Started",
		tags: ["Feature"],
		assignee: "Bob Brown",
		priority: "High",
	},
	{
		id: "static-037",
		lastUpdated: "1733402160000",
		text: "Build export functionality",
		status: "In Progress",
		tags: ["Feature"],
		assignee: "John Doe",
		priority: "Medium",
	},
	{
		id: "static-038",
		lastUpdated: "1733402220000",
		text: "Integrate import system",
		status: "Completed",
		tags: ["Feature", "Refactoring"],
		assignee: "Jane Smith",
		priority: "High",
	},
	{
		id: "static-039",
		lastUpdated: "1733402280000",
		text: "Validate settings schema",
		status: "Cancelled",
		tags: ["Testing"],
		assignee: "Alice Johnson",
		priority: "Low",
	},
	{
		id: "static-040",
		lastUpdated: "1733402340000",
		text: "Audit permissions logic",
		status: "Not Started",
		tags: ["Refactoring", "Documentation"],
		assignee: "Bob Brown",
		priority: "Medium",
	},
	{
		id: "static-041",
		lastUpdated: "1733402400000",
		text: "Implement logging service",
		status: "In Progress",
		tags: ["Feature"],
		assignee: "John Doe",
		priority: "High",
	},
	{
		id: "static-042",
		lastUpdated: "1733402460000",
		text: "Fix caching issues",
		status: "Completed",
		tags: ["Bug"],
		assignee: "Jane Smith",
		priority: "High",
	},
	{
		id: "static-043",
		lastUpdated: "1733402520000",
		text: "Refactor pagination logic",
		status: "Not Started",
		tags: ["Refactoring"],
		assignee: "Alice Johnson",
		priority: "Medium",
	},
	{
		id: "static-044",
		lastUpdated: "1733402580000",
		text: "Add validation messages",
		status: "In Progress",
		tags: ["Feature", "Bug"],
		assignee: "Bob Brown",
		priority: "Low",
	},
	{
		id: "static-045",
		lastUpdated: "1733402640000",
		text: "Update error handling",
		status: "Completed",
		tags: ["Refactoring"],
		assignee: "John Doe",
		priority: "High",
	},
	{
		id: "static-046",
		lastUpdated: "1733402700000",
		text: "Remove testing utilities",
		status: "Cancelled",
		tags: ["Testing", "Other"],
		assignee: "Jane Smith",
		priority: "Medium",
	},
	{
		id: "static-047",
		lastUpdated: "1733402760000",
		text: "Optimize documentation build",
		status: "Not Started",
		tags: ["Documentation"],
		assignee: "Alice Johnson",
		priority: "Low",
	},
	{
		id: "static-048",
		lastUpdated: "1733402820000",
		text: "Debug deployment script",
		status: "In Progress",
		tags: ["Bug"],
		assignee: "Bob Brown",
		priority: "High",
	},
	{
		id: "static-049",
		lastUpdated: "1733402880000",
		text: "Test monitoring integration",
		status: "Completed",
		tags: ["Testing"],
		assignee: "John Doe",
		priority: "Medium",
	},
	{
		id: "static-050",
		lastUpdated: "1733402940000",
		text: "Review analytics dashboard",
		status: "Not Started",
		tags: ["Feature", "Documentation"],
		assignee: "Jane Smith",
		priority: "High",
	},
	{
		id: "static-051",
		lastUpdated: "1733403000000",
		text: "Deploy performance fixes",
		status: "In Progress",
		tags: ["Bug"],
		assignee: "Alice Johnson",
		priority: "High",
	},
	{
		id: "static-052",
		lastUpdated: "1733403060000",
		text: "Configure security headers",
		status: "Completed",
		tags: ["Feature"],
		assignee: "Bob Brown",
		priority: "Medium",
	},
	{
		id: "static-053",
		lastUpdated: "1733403120000",
		text: "Migrate accessibility fixes",
		status: "Cancelled",
		tags: ["Bug", "Refactoring"],
		assignee: "John Doe",
		priority: "Low",
	},
	{
		id: "static-054",
		lastUpdated: "1733403180000",
		text: "Document mobile view API",
		status: "Not Started",
		tags: ["Documentation"],
		assignee: "Jane Smith",
		priority: "High",
	},
	{
		id: "static-055",
		lastUpdated: "1733403240000",
		text: "Analyze authentication logs",
		status: "In Progress",
		tags: ["Other"],
		assignee: "Alice Johnson",
		priority: "Medium",
	},
	{
		id: "static-056",
		lastUpdated: "1733403300000",
		text: "Design database schema",
		status: "Completed",
		tags: ["Feature", "Documentation"],
		assignee: "Bob Brown",
		priority: "High",
	},
	{
		id: "static-057",
		lastUpdated: "1733403360000",
		text: "Build API gateway",
		status: "Not Started",
		tags: ["Feature"],
		assignee: "John Doe",
		priority: "High",
	},
	{
		id: "static-058",
		lastUpdated: "1733403420000",
		text: "Integrate UI framework",
		status: "In Progress",
		tags: ["Feature", "Refactoring"],
		assignee: "Jane Smith",
		priority: "Medium",
	},
	{
		id: "static-059",
		lastUpdated: "1733403480000",
		text: "Validate dashboard data",
		status: "Completed",
		tags: ["Testing"],
		assignee: "Alice Johnson",
		priority: "Low",
	},
	{
		id: "static-060",
		lastUpdated: "1733403540000",
		text: "Audit reports generation",
		status: "Cancelled",
		tags: ["Testing", "Other"],
		assignee: "Bob Brown",
		priority: "High",
	},
	{
		id: "static-061",
		lastUpdated: "1733403600000",
		text: "Implement notifications service",
		status: "Not Started",
		tags: ["Feature"],
		assignee: "John Doe",
		priority: "Medium",
	},
	{
		id: "static-062",
		lastUpdated: "1733403660000",
		text: "Fix search indexing",
		status: "In Progress",
		tags: ["Bug"],
		assignee: "Jane Smith",
		priority: "High",
	},
	{
		id: "static-063",
		lastUpdated: "1733403720000",
		text: "Refactor filters logic",
		status: "Completed",
		tags: ["Refactoring"],
		assignee: "Alice Johnson",
		priority: "Medium",
	},
	{
		id: "static-064",
		lastUpdated: "1733403780000",
		text: "Add export formats",
		status: "Not Started",
		tags: ["Feature", "Documentation"],
		assignee: "Bob Brown",
		priority: "Low",
	},
	{
		id: "static-065",
		lastUpdated: "1733403840000",
		text: "Update import validation",
		status: "In Progress",
		tags: ["Bug", "Feature"],
		assignee: "John Doe",
		priority: "High",
	},
	{
		id: "static-066",
		lastUpdated: "1733403900000",
		text: "Remove settings migration",
		status: "Completed",
		tags: ["Refactoring"],
		assignee: "Jane Smith",
		priority: "Medium",
	},
	{
		id: "static-067",
		lastUpdated: "1733403960000",
		text: "Optimize permissions check",
		status: "Cancelled",
		tags: ["Bug"],
		assignee: "Alice Johnson",
		priority: "High",
	},
	{
		id: "static-068",
		lastUpdated: "1733404020000",
		text: "Debug logging output",
		status: "Not Started",
		tags: ["Bug", "Testing"],
		assignee: "Bob Brown",
		priority: "Low",
	},
	{
		id: "static-069",
		lastUpdated: "1733404080000",
		text: "Test caching layer",
		status: "In Progress",
		tags: ["Testing"],
		assignee: "John Doe",
		priority: "Medium",
	},
	{
		id: "static-070",
		lastUpdated: "1733404140000",
		text: "Review pagination UX",
		status: "Completed",
		tags: ["Feature", "Other"],
		assignee: "Jane Smith",
		priority: "High",
	},
	{
		id: "static-071",
		lastUpdated: "1733404200000",
		text: "Deploy validation rules",
		status: "Not Started",
		tags: ["Feature"],
		assignee: "Alice Johnson",
		priority: "High",
	},
	{
		id: "static-072",
		lastUpdated: "1733404260000",
		text: "Configure error tracking",
		status: "In Progress",
		tags: ["Feature"],
		assignee: "Bob Brown",
		priority: "Medium",
	},
	{
		id: "static-073",
		lastUpdated: "1733404320000",
		text: "Migrate testing suite",
		status: "Completed",
		tags: ["Testing", "Refactoring"],
		assignee: "John Doe",
		priority: "Low",
	},
	{
		id: "static-074",
		lastUpdated: "1733404380000",
		text: "Document documentation style",
		status: "Cancelled",
		tags: ["Documentation"],
		assignee: "Jane Smith",
		priority: "Medium",
	},
	{
		id: "static-075",
		lastUpdated: "1733404440000",
		text: "Analyze deployment metrics",
		status: "Not Started",
		tags: ["Other"],
		assignee: "Alice Johnson",
		priority: "High",
	},
	{
		id: "static-076",
		lastUpdated: "1733404500000",
		text: "Design monitoring dashboard",
		status: "In Progress",
		tags: ["Feature", "Documentation"],
		assignee: "Bob Brown",
		priority: "High",
	},
	{
		id: "static-077",
		lastUpdated: "1733404560000",
		text: "Build analytics pipeline",
		status: "Completed",
		tags: ["Feature"],
		assignee: "John Doe",
		priority: "Medium",
	},
	{
		id: "static-078",
		lastUpdated: "1733404620000",
		text: "Integrate performance tools",
		status: "Not Started",
		tags: ["Feature", "Testing"],
		assignee: "Jane Smith",
		priority: "High",
	},
	{
		id: "static-079",
		lastUpdated: "1733404680000",
		text: "Validate security audit",
		status: "In Progress",
		tags: ["Testing"],
		assignee: "Alice Johnson",
		priority: "Low",
	},
	{
		id: "static-080",
		lastUpdated: "1733404740000",
		text: "Audit accessibility compliance",
		status: "Completed",
		tags: ["Bug", "Documentation"],
		assignee: "Bob Brown",
		priority: "Medium",
	},
	{
		id: "static-081",
		lastUpdated: "1733404800000",
		text: "Implement mobile responsive",
		status: "Cancelled",
		tags: ["Feature"],
		assignee: "John Doe",
		priority: "High",
	},
	{
		id: "static-082",
		lastUpdated: "1733404860000",
		text: "Fix authentication timeout",
		status: "Not Started",
		tags: ["Bug"],
		assignee: "Jane Smith",
		priority: "High",
	},
	{
		id: "static-083",
		lastUpdated: "1733404920000",
		text: "Refactor database queries",
		status: "In Progress",
		tags: ["Refactoring"],
		assignee: "Alice Johnson",
		priority: "Medium",
	},
	{
		id: "static-084",
		lastUpdated: "1733404980000",
		text: "Add API rate limiting",
		status: "Completed",
		tags: ["Feature", "Bug"],
		assignee: "Bob Brown",
		priority: "High",
	},
	{
		id: "static-085",
		lastUpdated: "1733405040000",
		text: "Update UI theme",
		status: "Not Started",
		tags: ["Feature"],
		assignee: "John Doe",
		priority: "Low",
	},
	{
		id: "static-086",
		lastUpdated: "1733405100000",
		text: "Remove dashboard widgets",
		status: "In Progress",
		tags: ["Refactoring", "Other"],
		assignee: "Jane Smith",
		priority: "Medium",
	},
	{
		id: "static-087",
		lastUpdated: "1733405160000",
		text: "Optimize reports query",
		status: "Completed",
		tags: ["Bug"],
		assignee: "Alice Johnson",
		priority: "High",
	},
	{
		id: "static-088",
		lastUpdated: "1733405220000",
		text: "Debug notifications queue",
		status: "Cancelled",
		tags: ["Bug", "Testing"],
		assignee: "Bob Brown",
		priority: "Medium",
	},
	{
		id: "static-089",
		lastUpdated: "1733405280000",
		text: "Test search algorithms",
		status: "Not Started",
		tags: ["Testing"],
		assignee: "John Doe",
		priority: "High",
	},
	{
		id: "static-090",
		lastUpdated: "1733405340000",
		text: "Review filters documentation",
		status: "In Progress",
		tags: ["Documentation"],
		assignee: "Jane Smith",
		priority: "Low",
	},
	{
		id: "static-091",
		lastUpdated: "1733405400000",
		text: "Deploy export service",
		status: "Completed",
		tags: ["Feature"],
		assignee: "Alice Johnson",
		priority: "Medium",
	},
	{
		id: "static-092",
		lastUpdated: "1733405460000",
		text: "Configure import scheduler",
		status: "Not Started",
		tags: ["Feature", "Documentation"],
		assignee: "Bob Brown",
		priority: "High",
	},
	{
		id: "static-093",
		lastUpdated: "1733405520000",
		text: "Migrate settings storage",
		status: "In Progress",
		tags: ["Refactoring"],
		assignee: "John Doe",
		priority: "High",
	},
	{
		id: "static-094",
		lastUpdated: "1733405580000",
		text: "Document permissions matrix",
		status: "Completed",
		tags: ["Documentation"],
		assignee: "Jane Smith",
		priority: "Medium",
	},
	{
		id: "static-095",
		lastUpdated: "1733405640000",
		text: "Analyze logging patterns",
		status: "Cancelled",
		tags: ["Other", "Testing"],
		assignee: "Alice Johnson",
		priority: "Low",
	},
	{
		id: "static-096",
		lastUpdated: "1733405700000",
		text: "Design caching strategy",
		status: "Not Started",
		tags: ["Feature"],
		assignee: "Bob Brown",
		priority: "High",
	},
	{
		id: "static-097",
		lastUpdated: "1733405760000",
		text: "Build pagination component",
		status: "In Progress",
		tags: ["Feature"],
		assignee: "John Doe",
		priority: "Medium",
	},
	{
		id: "static-098",
		lastUpdated: "1733405820000",
		text: "Integrate validation library",
		status: "Completed",
		tags: ["Feature", "Refactoring"],
		assignee: "Jane Smith",
		priority: "High",
	},
	{
		id: "static-099",
		lastUpdated: "1733405880000",
		text: "Validate error messages",
		status: "Not Started",
		tags: ["Testing", "Bug"],
		assignee: "Alice Johnson",
		priority: "Low",
	},
	{
		id: "static-100",
		lastUpdated: "1733405940000",
		text: "Audit testing coverage",
		status: "In Progress",
		tags: ["Testing", "Documentation"],
		assignee: "Bob Brown",
		priority: "Medium",
	},
];
